// country-codes.js
const countryCodes = [
    { name: "India", code: "91" },
    { name: "Afghanistan", code: "93" },
    { name: "Albania", code: "355" },
    { name: "Algeria", code: "213" },
    { name: "Argentina", code: "54" },
    { name: "Australia", code: "61" },
    { name: "Austria", code: "43" },
    { name: "Belgium", code: "32" },
    { name: "Brazil", code: "55" },
    { name: "Canada", code: "1" },
    { name: "Chile", code: "56" },
    { name: "China", code: "86" },
    { name: "Colombia", code: "57" },
    { name: "Costa Rica", code: "506" },
    { name: "Denmark", code: "45" },
    { name: "Egypt", code: "20" },
    { name: "Finland", code: "358" },
    { name: "France", code: "33" },
    { name: "Germany", code: "49" },
    { name: "Greece", code: "30" },
    { name: "Hong Kong", code: "852" },
    { name: "Indonesia", code: "62" },
    { name: "Ireland", code: "353" },
    { name: "Italy", code: "39" },
    { name: "Japan", code: "81" },
    { name: "Malaysia", code: "60" },
    { name: "Mexico", code: "52" },
    { name: "Netherlands", code: "31" },
    { name: "New Zealand", code: "64" },
    { name: "Nigeria", code: "234" },
    { name: "Norway", code: "47" },
    { name: "Pakistan", code: "92" },
    { name: "Philippines", code: "63" },
    { name: "Poland", code: "48" },
    { name: "Portugal", code: "351" },
    { name: "Russia", code: "7" },
    { name: "Singapore", code: "65" },
    { name: "South Africa", code: "27" },
    { name: "South Korea", code: "82" },
    { name: "Spain", code: "34" },
    { name: "Sweden", code: "46" },
    { name: "Switzerland", code: "41" },
    { name: "Taiwan", code: "886" },
    { name: "Thailand", code: "66" },
    { name: "Turkey", code: "90" },
    { name: "UAE", code: "971" },
    { name: "UK", code: "44" },
    { name: "USA", code: "1" },
    { name: "Custom Code", code: "custom" }
];
